### ISSUE TITLE
Add Illumina Library Entity Step - Convert cDNA Entity Types to Illumina Libraries

### ISSUE THREAD

**Issue by LMT337** [GTAC-MGI/GTAC-ESP-LIMS#101]
SEQ workflow chain only takes Illumina Library Entity types. Need to add or update SC Protocol to convert cDNA Entity Types into Illumina Library types.

**Comment by tim-snyder-wustl** [comment]
Be sure to remove the unnecessary library bardcode field from the next-to-last protocols (before the newly-created sample protocols).

**Comment by tim-snyder-wustl** [comment]
~~Removing `SC Lab: Send to Seq` workflow, adding new `SC Lab: Create Illumina Library` workflow.~~ Will handle sending library off to Sequencing WF Chain in this new workflow, on this ticket: https://github.com/GTAC-MGI/GTAC-ESP-LIMS/issues/52

**Comment by tim-snyder-wustl** [comment]
SC will get cells, nuclei, or cDNA, but will only ever enter cDNA into ESP.

- Need to add a sample protocol to convert cDNA to Illumina Library at the end of each workflow, before Barcoding step takes place.
- ~~Each sample will be a 1-to-many (fan out), except for the 'Only' workflows, which are 1-to-1.~~ Each sample protocol is actually 1-to-1, its just that a workflow can be repeated multiple times, generating a new library each time.
- Then need to make the 'Dilutions' workflow optional.
