### ISSUE TITLE
Write script to generate custom content.yml

### ISSUE THREAD

**Issue by tim-snyder-wustl** [GTAC-MGI/GTAC-ESP-LIMS#102]
Because importing all yaml files is beginning to take an extended length of time, develop a solution to generate custom content.yml file that only contains references to yaml for a particular lab that is being worked on, to cut down on these lengthy import times.

**Comment by LMT337** [comment]
Planned implementation: 

-mv content.yml to master.content.yml (possibly in subdir)
-create new content.yml with only user specified workflows (SC, DNA etc..)
-Add option to update content.yml with newly exported files from ESP

**Comment by LMT337** [comment]
content_yaml_parser.py

Run from washu_gtac directory

usage:
-labs/-l option takes a comma separated list of libs to import

Example to import single cell and sequencing workflows only: 
python utils/content_yaml_parser.py -l sc,seq

Then run `make install` 

To restore the content.yaml file back to it's normal configuration, use the --restore/-r flag:

python utils/content_yaml_parser.py -r

** The --restore function MUST be run prior to creating a new -l content.yaml file.
