### ISSUE TITLE
Implement Index and Cycle number selection

### ISSUE THREAD

**Issue by tim-snyder-wustl** [GTAC-MGI/GTAC-ESP-LIMS#107]
Jen:

Cycle number just needs to be a field where we can enter a numerical value next to the index field.  That would need to be added at the Sample Index PCR step right next to the index selection.
 
I would like to be able to scan the index for each sample from the 2D tube and it autopopulate into the field, but I would also like a drop down menu that is searchable where it will pop up quickly once you start typing it in.   This is also in the Sample Index PCR step.

**Comment by LMT337** [comment]
New plate of indexes: 
Need plate barcode for plate of 96 2D tubes
scan the plate of 2D barcodes, those will be linked to the plate barcode. 

In the lab...you want options to either scan the well barcode and populate the linked plate well barcode in a field OR you want a drop down where you can pick from an abbreviated name linked to a well position (TT-A1). 

want to count each time the index is used - maximum of three alliquots. 

This index infrormation will be stored in Firebase. 

going to need a plate import workflow, does not need to be attached to SC workflow chain.

**Comment by LMT337** [comment]
Workflow plate import here: 
http://sandbox5.wucon.wustl.edu:11702/#/builders/workflows/details/c555f4c4-b269-4d76-998c-fde4abd5c469
