### ISSUE TITLE
Fix Seq Lab Protocol names

### ISSUE THREAD

**Issue by tim-snyder-wustl** [GTAC-MGI/GTAC-ESP-LIMS#121]
<img width="410" alt="Screen Shot 2022-09-23 at 11 11 02 AM" src="https://user-images.githubusercontent.com/91081406/192005717-455a1857-139f-4f19-b286-c24c10f76692.png">

Note: KAPA names and files will be updated in a different ticket to avoid git merge issues.

**Comment by LMT337** [comment]
Names in Protocols and Workflows updates to be in line with standards.  Formulas also updated to reflect standards update.  Make Install passes without issue using a clean env.  Will need feedback from SEQ group to confirm Protocol cell references are correct.
