### ISSUE TITLE
Smartsheet Notification Module To Notify SEQ

### ISSUE THREAD

**Issue by LMT337** [GTAC-MGI/GTAC-ESP-LIMS#135]

**Comment by LMT337** [comment]
Building notification module to work with https://github.com/GTAC-MGI/GTAC-ESP-LIMS/issues/52

**Comment by tim-snyder-wustl** [comment]
Smartsheet here: https://app.smartsheet.com/sheets/XJPW6qGHxJ4jCcRcjg2mjCRrCmCcWRXXX9JmgCQ1?view=grid
