### ISSUE TITLE
DNA Lab Assessment: Dilution Pipeline Protocol

### ISSUE THREAD

**Issue by tim-snyder-wustl** [GTAC-MGI/GTAC-ESP-LIMS#149]
DNA Lab: Assessment Workflow
http://sandbox5.wucon.wustl.edu:11702/#/builders/workflows/details/dc1b23d8-ceb6-43eb-a1f7-db929477ca8c

*Note:* should be done in tandem with: https://github.com/GTAC-MGI/GTAC-ESP-LIMS/issues/148

* (DNA Lab Assessment 2 ?) - This protocol should be used for the csv upload.  It is our understanding that it needs a pipeline protocol and cannot be done in the DNA Lab Assessment protocol. Upload for Varioskan or Qubit. Pass or fail based on threshold. https://wustl.app.box.com/file/1030358995977 https://wustl.app.box.com/file/1030357771604 

* Assessment Dilution Barcode - We discussed with Lee and Tim scanning the source barcode for the qubit or vario and not necessarily barcoding a dilution, but using it virtually for the calculations.  Example:  If using a 1:2 dilution you would multiply your raw concentration result by 2.

* Assessment Results File - This should be where the csv upload information is???

* Remaining Volume (µl) -  Calculation should be done here by subtracting the sample transfer volume value (default being 1)

* (DNA Lab: Assessment 2) We would like L7 to autogenerate dilution factor based on submitted collaborator concentrations.  We need the ability to edit dilution, if needed.  [Calculate Dilution Factor
](https://wustl.app.box.com/file/1032232200453)

* Instrument Type - If we choose Qubit then can the kit be linked here and if we choose vario link the kit here, etc

**Comment by tim-snyder-wustl** [comment]
[qubit flex.csv](https://github.com/GTAC-MGI/GTAC-ESP-LIMS/files/11043382/qubit.flex.csv)
[vario.xls](https://github.com/GTAC-MGI/GTAC-ESP-LIMS/files/11043383/vario.xls)

**Comment by billtell** [comment]
per Tracie: qubit assessment is **MUST** have, vario is nice-to-have for MVP.
Therefore, focusing development primarily for Qubit

**Comment by billtell** [comment]
per Tracie: minimum thresholds for pass/fail are based on library type.  
She has provided a spreadsheet for reference: https://wustl.box.com/s/8tbzyr2x85b6nz6cr8s7ofq8umwyx1tj

**Comment by billtell** [comment]
[#234](https://github.com/GTAC-MGI/GTAC-ESP-LIMS/issues/234 ) Has been created to incorporate Varioskan.
