### ISSUE TITLE
DNA Lab Ingest QC Results (Bioanalyzer/Flash Gel)

### ISSUE THREAD

**Issue by tim-snyder-wustl** [GTAC-MGI/GTAC-ESP-LIMS#152]
DNA Lab: Fragmentation QC Workflow
http://sandbox5.wucon.wustl.edu:11702/#/builders/workflows/details/2b3ffb24-86c8-48a1-aaf7-a4017522016c

Change pipeline protocol to standard protocol.

**Comment by LMT337** [comment]
DNA Bioanalzyer overlaps with RNA Bioanlazyer requirements, pdf files are able to be procesed for this images/stats etc..
