### ISSUE TITLE
DNA Lab: KAPA - Index Selection

### ISSUE THREAD

**Issue by tim-snyder-wustl** [GTAC-MGI/GTAC-ESP-LIMS#153]
DNA Lab: KAPA Hyper Amplified Workflow
DNA Lab: KAPA Hyper PCR Free Workflow

Barcoded indexes need associated to samples at these steps:

- DNA Lab: KAPA Hyper Automated
- DNA Lab: Kapa Hyper Amplified

In tandem with: https://github.com/GTAC-MGI/GTAC-ESP-LIMS/issues/177

**Comment by LMT337** [comment]
plate
i7 name
i5/i5 sequence
catted together

workflow: DNA Lab: KAPA Hyper Amplified
protocol: DNA Lab: KAPA Hyper

workflow: DNA Lab: KAPA Hyper PCR Free
protocol: DNA Lab: KAPA Hyper
