### ISSUE TITLE
DNA Lab: Capture - File Upload

### ISSUE THREAD

**Issue by tim-snyder-wustl** [GTAC-MGI/GTAC-ESP-LIMS#159]
DNA Lab: Capture Workflow
http://sandbox5.wucon.wustl.edu:11702/#/builders/workflows/details/187a700a-e545-4db4-a735-daae0a97aea5

Need to be able to upload optimization gels images (jpeg or pdf) - also not always done so should be an optional step

**Comment by billtell** [comment]
Confirmed with Nikki and Ryan that nothing will be done with jpg in this step.  The protocol already accommodates jpg and pdf attachment and 'Required' is not toggled so no changes were made to protocol at this time.
