### ISSUE TITLE
DNA Lab Assessment Barcoding Ingest / Sample Linkage

### ISSUE THREAD

**Issue by tim-snyder-wustl** [GTAC-MGI/GTAC-ESP-LIMS#164]
Ingest output CSV from VisionMate to map to samples in ESP or assign to wells manually via UI.

Relates to: https://github.com/GTAC-MGI/GTAC-ESP-LIMS/issues/175

**Comment by LMT337** [comment]
Ticket now incudes Ingest files from CRM for RNA/DNA.

**Comment by LMT337** [comment]
No meta data CRM file sent
Updated accessioning workflow
