### ISSUE TITLE
Add DNA Entity ID Sequence to DNA Entity

### ISSUE THREAD

**Issue by LMT337** [GTAC-MGI/GTAC-ESP-LIMS#187]
DNA Enity creates with ESP prefix.  Entity should create with DNA.  Possibly need to update GTAC ID with this update as well.

**Comment by tim-snyder-wustl** [comment]
Closing this ticket, making it a part of:
https://github.com/GTAC-MGI/GTAC-ESP-LIMS/issues/186
because I need to fix this before I can fix GTAC IDs.
