### ISSUE TITLE
Seq Lab: Ingest/2D barcode ingest - Libraries

### ISSUE THREAD

**Issue by tim-snyder-wustl** [GTAC-MGI/GTAC-ESP-LIMS#190]
New workflow:
- replicate Receive Library with a 2D barcode column
- waiting on list of columns to ingest for worksheet
- create pipeline to process ingest worksheet frm CRM.

**Comment by tim-snyder-wustl** [comment]
-

**Comment by LMT337** [comment]
Direct to seq file from Mike Schmidt: 
https://wustl.app.box.com/file/1219166393358?s=vlud78iwuajrl353ro9dea6ge9gsmpdx

**Comment by LMT337** [comment]
Process starts with Recieve Library: create two workflows one for Library Pools, one for Library
1D barcode not a requirement
Use these columns from DNA example for 2D import: Tube Label or External Barcode	2D Rack Holder	Well Location
Script to assign bc to well need to factor in plate name if there are multiple plates on ingest. 
Cut off Accessioning node.

**Comment by LMT337** [comment]
Refactor CRM Billing file ingest to be an imported class for all lab ingest workflows that saves with sample ingest file instead of saving with the CRM billing script process.  Reduces script run time as saving updated workflows is a time suck in ESP.

**Comment by LMT337** [comment]
Presented workflows to SEQ/PM, add file header checks for both seq ingest workflows and billing file class.
