### ISSUE TITLE
SC Lab: Enrichment Library Protocol

### ISSUE THREAD

**Issue by tim-snyder-wustl** [GTAC-MGI/GTAC-ESP-LIMS#204]
- Add column 'Enrichment Type' a dropdown to select TCR, BCR (TCR as default)

**Comment by billtell** [comment]
- TCR 1
- TCR 2
- BCR 1
- BCR 2

**Comment by billtell** [comment]
Workflows ? : 

- SC Lab: 5 v 2 GEX With 1 Enrichment TCR-BCR Feature TotalSeqC
- SC Lab: 5 v 2 GEX with 1 Enrichment TCR-BCR Feature TotalSeqC Existing cDNA
- SC Lab: 5 v 2 GEX With 2 Enrichments TCR-BCR Feature TotalSeqC
- SC Lab: 5 v 2 GEX with 2 Enrichments TCR-BCR Feature TotalSeqC Existing cDNA

**Comment by billtell** [comment]
Protocols ? :

- SC Lab: 5 prime Target Enrichment 1
- SC Lab: 5 prime Target Enrichment 2
- SC Lab: 5 prime Target Enrichment 1 2
- SC Lab: 5 prime Target Enrichment 2 2

**Comment by billtell** [comment]
being addressed on the 5' workflow reconfigure branch: #370
