### ISSUE TITLE
Seq Lab: Index checker for Receive Libraries

### ISSUE THREAD

**Issue by tim-snyder-wustl** [GTAC-MGI/GTAC-ESP-LIMS#213]
http://sandbox5.wucon.wustl.edu:11702/#/builders/workflows/details/91c4c5b9-71e4-4ce2-8a6e-a29066e0b19b

Error handler in CLE Lab: Targeted Capture Pooling - something that would not let you pool conflicting indexes

- Check in Library Construction nodes
- How to implement? Pipeline script? onChange JS? 
- https://javascript.info/file 
- https://stackoverflow.com/questions/1293147/how-to-parse-csv-data

**Comment by abohanno** [comment]
[CLE_IndexSequences.xlsx](https://github.com/GTAC-MGI/GTAC-ESP-LIMS/files/15263856/CLE_IndexSequences.xlsx)

**Comment by tim-snyder-wustl** [comment]
- Add JS fn to Ingest Protocol that will provide a separate button to check indexes
- Fn calls custom ESP endpoint that will query Firestore for the indexs
- Both regular index format and reverse complement should be checked for on Firestore
- Show a toast message if there are missing indexes, and highlight each cell red

**Comment by tim-snyder-wustl** [comment]
- Update Library & Pool Ingest for Seq

**Comment by tim-snyder-wustl** [comment]
- If an index is *not* in the DB, but its reverse complement *is*, indicate this in the error somehow.
- Check ATAC i5 and i7 indexes, as key-value stores, where one set of indexes is not like the other, throw error.

Example:

https://gtac-mgi-lims.wustl.edu/#/lims/worksheet/c9adabda-de0a-4c82-8c15-976f0a14ae5a

![Image](https://github.com/user-attachments/assets/c41f96ee-4c21-4848-9a66-a1b6f0d743e4)

**Comment by tim-snyder-wustl** [comment]
- Need to check the *combinations* of indexes for i7 + i5, and ATAC (i7, i7b, i7c, i7d)
- If a particular index is used in a particular combination, it must *always* be used in that combination!

**Comment by tim-snyder-wustl** [comment]
- Check expected index combinations - for each i7, if it has a combination pair in the 'Combined Index Sequence' column, check that the corresponding i5 is listed in the DB for the i7 index.
- Need to check for all 4 ATAC combinations as well!
