### ISSUE TITLE
CLE Lab: Sync 1-to-1 parent/child sample data

### ISSUE THREAD

**Issue by tim-snyder-wustl** [GTAC-MGI/GTAC-ESP-LIMS#220]
Add Button to syc parent/child entity data on Sample Protocols.

**Comment by billtell** [comment]
- [x] CLE Lab: Aliquot Source DNA 2
- [x] CLE Lab: EpMotion Dilution Setup
- [ ] CLE Lab: EpMotion Pooling Setup
- [x] CLE Lab: Haloplex Library Construction
- [x] CLE Lab: ILMN Library Construction
- [x] CLE Lab: KAPA Hyper Library Construction - moved hide columns from instructions to onrender
- [x] CLE Lab: Targeted Capture - no hide column on render.  needed?
- [ ] CLE Lab: Targeted Capture Pooling

**Comment by billtell** [comment]
need to confirm which protocols are Fan-In.

**Comment by billtell** [comment]
going to create 2 new tickets:

- [x] To sync child entity fields in pooling sample protocols

- CLE Lab: EpMotion Pooling Setup
- CLE Lab: Targeted Capture Pooling
- #288 

- [x] To update 'Remaining Value (µl)' at any point volume is being removed from the parent entity.
- #289
