### ISSUE TITLE
CLE Lab: Add picklist to Technician columns

### ISSUE THREAD

**Issue by tim-snyder-wustl** [GTAC-MGI/GTAC-ESP-LIMS#227]
Need clarification:

technician vs frag technician vs library technician?

**Comment by billtell** [comment]
add a dropdown based on list from Andy

**Comment by billtell** [comment]
drop down with Technician's initials added to these protocols:

- [x] 'CLE Lab: EpMotion Reagent Lot Tracking':
- [x] 'CLE Lab: Extraction Reagent Lot Tracking':
- [x] 'CLE Lab: Haloplex Reagent Lot Tracking':
- [x] 'CLE Lab: ILMN Libray Prep Reagent Lot Tracking':
- [x] 'CLE Lab: KAPA Hyper Reagent Lot Tracking':
- [x] 'CLE Lab: Library Assessment Reagent Lot Tracking':
- [x] 'CLE Lab: Qubit Assessment Reagent Lot Tracking':
- [x] 'CLE Lab: Specimen Assessment Reagent Lot Tracking':
- [x] 'CLE Lab: Targeted Capture Reagent Lot Tracking':

**Comment by billtell** [comment]
The placement of Technician columns may need to change.  If this is the case, will make a new ticket.
