### ISSUE TITLE
Dilution

### ISSUE THREAD

**Issue by tim-snyder-wustl** [GTAC-MGI/GTAC-ESP-LIMS#23]
Clone Manual Dilution steps from RNA workflow in Seq Pooling (SC does not do any library pooling, however).

**Comment by LMT337** [comment]
[Example_10nM dilution.xls](https://github.com/GTAC-MGI/GTAC-ESP-LIMS/files/8155621/Example_10nM.dilution.xls)

**Comment by tim-snyder-wustl** [comment]
Dilution Calculations:

    sample name
    DNA ng/μL: number
    size in bp: number
    DNA nM: (DNA ng/μL * (10^3/1) * (1/649) * (1/size in bp)) * 1000

    --

    200 μL of stock

    μL of 10nM stock: 200
    μL DNA: 2000 / nM DNA
    μL EB: μL of 10nM stock - μL DNA

    --

    custom volume of stock

    μL of 10nM stock: custom
    μL DNA: (μL of 10nM stock * 10) / nM DNA
    μL EB: ul of 10nM stock - μL DNA
