### ISSUE TITLE
Seq Lab: Write endpoint to ingest demux QC data and update Firestore and Smartsheet

### ISSUE THREAD

**Issue by tim-snyder-wustl** [GTAC-MGI/GTAC-ESP-LIMS#230]
## TODO: Break this up in to smaller tickets

---

### 1. On initial sample ingest
1. Initialize Firestore with new data
2. Initialize Smartsheet with new data

### 2. On ESP API call with QC data
1. Update Firestore
2. Update Smartsheet
3. Update LIMS worksheets

### 3. On ESP API call with completion of data transfer info
???

---

We need from Mark:

- Filepaths for FASTQ files, and which sample they belong to
- The actual QC stats
- SR# for samples

---

Show these Library QC Metrics:

https://wustl.app.box.com/file/950842021254

Example:

https://app.smartsheet.com/sheets/J7g3JgmFw7QFQmcFHqxqJFPF9p38rc7mg6GgJ541?view=grid

There should be combined totals for libraries that may have been run over multiple lanes as well.

Write QC data to Firestore and update Smartsheet.

Will need to update Firestore to show which samples failed in ESP when adding new data. See if the sample failed made it at all to sequencing.

Smartsheet will *only* be updated when Firestore is updated.

Will then need to update LIMS worksheets with the appropriate QC data.

---

Need

- SR # associated with QC metrics
- Sample Name / ID

[dragen_Reports.tar.gz](https://github.com/GTAC-MGI/GTAC-ESP-LIMS/files/11354526/dragen_Reports.tar.gz)

**Comment by LMT337** [comment]
Smartsheet requirements: 

Check if SR exists, if not, create Parent row with high level project data including DT/Analaysis reqs.
Then add children rows of samples that have completed QC w/QC metrics. 

If SR exists, iterate over child sample rows, if child sample already in SS update QC data, if not, add new child row with QC data. 

Add pass/fail status looking at QC metrics.

**Comment by LMT337** [comment]
DT Complete - L7 either experiments or samples  somewhere? should be marked as DT complete for Project Management tracking.

**Comment by tim-snyder-wustl** [comment]
Breaking ticket up into smaller tickets. Closing.
