### ISSUE TITLE
DNA Lab: Add Sample Name to every protocol

### ISSUE THREAD

**Issue by tim-snyder-wustl** [GTAC-MGI/GTAC-ESP-LIMS#242]

**Comment by LMT337** [comment]
Added Sample Name column to every dna_* protocol that did not have Sample Name column.  Fixed Well Dropdown picklist in
DNA Lab: WGBS Methyl-Seq Library Construction to use esp expression instead of individual strings.
- Index Well Location:
        dropdown: "{{ ['%s0%d' % (row, col) for row in 'ABCDEFGH' for col in range(1, 13)] }}"
        rule: dropdown
        visible: true

**Comment by LMT337** [comment]
Tested with make install before merging to release-10 branch
