### ISSUE TITLE
SC Working Session #2

### ISSUE THREAD

**Issue by LMT337** [GTAC-MGI/GTAC-ESP-LIMS#271]
- SC Lab: 5 v 2 GEX With 2 Enrichments TCR-BCR Feature TotalSeqC - Original Entity, that is moved to another tube. 
Feature workflows generate TWO Enties at this stage. Both are cDNA but on is marked as Feature. Other workflows that are not feature do NOT generate two Entities and may not need another Entity at this stage, just the BC updated. 

- Remove Indexes from  SC Lab: 5 prime Sample Feature Index PCR Mix

- Removed Transferred Supernatant Cleaup-lot# from SC Lab: 5 prime Sample Feature Index PCR Mix Reagents

- 'SC Lab: 5 prime Index and Amplification Cycles' Add Index columns here

- 'SC Lab: 5 prime Qubit and Agilent' - Needs Onchange that does this calc:
Qubit (ng/ul) * 35 = Final Yield ng(35ul)

- Qubit and Agilent protocols need Protocol columnn 

 - Agilent.pdf:
      rule: attachment
      shared: true

- 'SC Lab: 5 prime Feature Library Barcode' - Additional field to populate from parent:

~~All of the billing info~~
Index information
~~Species~~
use: `onrender_populate_child_sample_fields_and_index()`

---

Reference ticket
https://github.com/orgs/GTAC-MGI/projects/2/views/24?pane=issue&itemId=25475562
~~Hide fields:  UUI, Client Assesed Conc, Client Assessed Molarity, Sequencing Recipe, Requested Amount of Flow cell, Desired Fold Coverage, Requested Number of Reads, Pool Name, Flow Cell~~

Average Library Size needs to be pulled from 'SC Lab: 5 prime Qubit and Agilent'

**Comment by tim-snyder-wustl** [comment]
Crossed out tasks that will be completed in this ticket:
https://github.com/GTAC-MGI/GTAC-ESP-LIMS/issues/202

**Comment by LMT337** [comment]
Still unsure about index cols, updated as best I could. 
Added calc to onchange in col instead of function in invokables.

**Comment by LMT337** [comment]
Added missiing pdf col. 

Skipping addition fields from parent for now. Circle back when Entities are resolved.
