### ISSUE TITLE
Seq Lab: Create Freezer Types (Rack, Small/large -20)

### ISSUE THREAD

**Issue by LMT337** [GTAC-MGI/GTAC-ESP-LIMS#279]
Create Freezer objects for Seq Lab plate/tube check in out.

**Comment by LMT337** [comment]
Freezer requirements from Matt:
https://wustl.app.box.com/file/1253707324907

**Comment by LMT337** [comment]
Do these objects need Entity fields?

**Comment by LMT337** [comment]
Should container types ONLY take Entites per lab?  Maybe not freezers but lab specific 96/384 well plates?

**Comment by LMT337** [comment]
Need to follow up with L7 on how to export exisiting containers and set them to create with make install.  Confirm that contents of container will not be overwritten if contianer is imported again.

**Comment by LMT337** [comment]
After ESP container feedback, put containter file (if it's possible) here:
content/inventory/container_types.yml

**Comment by LMT337** [comment]
Create shelf object to put in freezers

**Comment by billtell** [comment]
Need to check with L7 regarding import existing implementation of freezers
submitted request(7/20): https://support.l7informatics.com/hc/en-us/requests/2344

**Comment by billtell** [comment]
Export container objects for Large and Small(x2) Seq Freezers and added models to content.yaml

**Comment by billtell** [comment]
Based on feeback from L7, large freezer (Seqlab3) is now filled with the 5 shelves after a make install.
