### ISSUE TITLE
Seq Lab: Dilutions bug

### ISSUE THREAD

**Issue by tim-snyder-wustl** [GTAC-MGI/GTAC-ESP-LIMS#298]
Remaining Volume (ul) for the dilutions just created on the [SEQ Lab: Manual Illumina Dilutions Create Dilutions](https://gtac-mgi-lims.wustl.edu/#/builders/protocols/details/ddcd8b14-46a6-4ea4-8933-26e338a86b61) protocol is being populate with the volume of the parent instead of the volume just created in the previous protocol (in this case they should all be 30ul).

![Image](https://github.com/GTAC-MGI/GTAC-ESP-LIMS/assets/91081406/866f6417-21c8-48fe-8412-70a36ee903e3)

**Comment by tim-snyder-wustl** [comment]
@mcordes-gtac Can you help me clarify things here? It appears that everything is working as expected.

In the first setup protocol, remaining volume is calculated when you hit the blue 'Update Dilution Data' button. It is based on the simple formula: 'Volume (µl) - Volume to Add (µl)'. The field is hidden in the protocol, it's only there to be pulled in to the next one, but from the right panel in the worksheet you can unhide it. Is this correct?

In the next protocol where the dilution is created, remaining volume is pulled in from the previous protocol via a protocol link. Is this correct?

https://gtac-mgi-lims.wustl.edu/#/builders/workflows/details/48e23d07-08aa-4002-bb50-d58a256f2fdd



![Image](https://github.com/GTAC-MGI/GTAC-ESP-LIMS/assets/91081406/60856dc9-ca56-4f42-b016-a0044eecc06a)

**Comment by mcordes-gtac** [comment]
@tim-snyder-wustl Remaining volume in the previous protocol (SEQ Lab: Manual Illumina Dilutions Setup)applies to the parent of the dilution. In the protocol I pointed out (SEQ Lab: Manual Illumina Dilutions Create Dilutions), remaining volume should refer to the dilution just created from the parent. In which case, it should be Normalized Volume (ul) from the previous protocol.  That help?

**Comment by tim-snyder-wustl** [comment]
@mcordes-gtac Ok I'll link 'Remaining Volume' to 'Normalized Volume' in the previous protocol. Thanks!
