### ISSUE TITLE
CLE Lab: Specimen Assessment pt.1

### ISSUE THREAD

**Issue by billtell** [GTAC-MGI/GTAC-ESP-LIMS#307]
Tasks:

- [x]  Remove '2D Barcode' column from 'CLE Lab: Specimen Assessment' protocol
- [x] Remove '2D Barcode' column from 'CLE Lab: Extraction Reagent Lot Tracking' protocol
- [x] Remove 'TCP' assay, replace with 'SOMA', make sure all assays are up to date
- [x] Add Tissue Type column to assessment protocol.  pass/fail determined in part by assay & tissue
- [x]  Add a blank value for Pass/Fail if an automated value cannot be determined
- [x] Restrict file types to `.csv` and `.xml`
- [x] Add .xml parsing function for nanodrop 
- [ ]  Confirm the format of the tsv that can / will be exported from nanodrop
- [x] Adjust Qubit to map results based on lims worksheet index position instead of sample name
- [x] Revised pass/fail criteria (see below)
- [ ] Adjust pipeline yaml to output report to pipeline window
- [ ] Format output report to match criteria (need to add volumne column)
- [x] Update Qubit parser to target `Original Sample Conc.` column
- [x] Add a 'Fail Reason' column that populates on the metric the sample was failed on

**Comment by billtell** [comment]
Revised pass/fail criteria:

 
IDT Exome Clearance Assay:

>1000ng for bone marrow and peripheral blood specimens

>500ng for buccal swab specimens

IDT Tumor-Normal Exome Assay:

>500ng

SOMA Assay:

>1000ng for peripheral blood specimens

>500ng for all other specimen types

For aliquot specimens, include that amount as well. (This will be hard to incorporate, as long as we can override the pass/fail we should be fine)

IDT Germline Exome Assay:

>1000ng for peripheral blood specimens

>500ng for buccal swab specimens

For aliquot specimens, include that amount as well. (This will be hard to incorporate, as long as we can override the pass/fail we should be fine)

Gateway Seq Assay:

>500ng

MyeloSeq Assay:

≥750ng

MyeloSeq/ChromoSeq Assay:

≥1500ng

ChromoSeq Assay:

≥750ng

**Comment by billtell** [comment]
For UDN Extractions:

The QC threshold for UDN assessments is >15ug.

I am setting the threshold to 15,000ng

**Comment by billtell** [comment]
Nanodrop Files:


Qubit Files:

**Comment by billtell** [comment]
- [ ] Extraction Volume QC metrics:

- QIACube DNA (blood and bone marrow eluted in 100uL, 1 reaction): QC Range = 50uL - 125uL
- QIACube DNA (blood and bone marrow eluted in 100uL, 2 reactions): QC Range = 150uL - 225uL
- QIACube DNA (blood and bone marrow eluted in 100uL, 3 reactions): QC Range = 250uL - 325uL
- QIACube DNA (blood and bone marrow eluted in 100uL, 4 reactions): QC Range = 350uL - 425uL

- Manual Prep DNA (fresh tissue and FFPE eluted in 60uL): QC Range = 40uL – 70uL 
- Manual Prep DNA (Buccal Swabs eluted in 150uL, 2 reactions pooled): QC Range = 250uL – 310uL
- Manual Prep DNA (cell pellets and fibroblasts eluted in 200uL): QC Range = 150uL – 225uL

**Comment by abohanno** [comment]
[Example Nanodrop File MS232_030123_KLS.xlsx](https://github.com/GTAC-MGI/GTAC-ESP-LIMS/files/15265718/Example.Nanodrop.File.MS232_030123_KLS.xlsx)
***The above file was originally an XML file***


[Example Qubit File QubitData_27-12-2022_10-10-36.csv](https://github.com/GTAC-MGI/GTAC-ESP-LIMS/files/15265720/Example.Qubit.File.QubitData_27-12-2022_10-10-36.csv)

**Comment by billtell** [comment]
@abohanno I have something n my notes stating that nanodrop files are exportable as tsv files as well.
Is that true and can that format be used in for the pipeline?

**Comment by abohanno** [comment]
I will have to check to be sure. If XML is our only option, would re-saving as an xlsx or csv work before uploading?

**Comment by billtell** [comment]
- [ ] Raise an error if Assay and Tissue Type are blank.  PASS/FAIL can't be determined with out it.
- [x] Maybe add drop-down menus for both Assay and Tissue Type into `CLE Lab: Specimen Assessment` protocol in case they do not get set in Accessioning

**Comment by abohanno** [comment]
Hi All,

**Updated QC metrics for specimen assessment listed below:**

- IDT Tumor-Normal = Yield >250ng, 260/280 = 1.4 - 2.4
- SOMA = Yield >250ng, 260/280 = 1.4 - 2.4
- IDT Germline Exome = Yield >250ng, 260/280 = 1.4 - 2.4
- Gateway Seq = Yield >250ng, 260/280 = 1.4 - 2.4
- MyeloSeq = Yield >250ng, 260/280 = 1.4 - 2.4 (any MyeloSeq that is also a ChromoSeq should have >500ng)
- ChromoSeq = Yield >250ng, 260/280 = 1.4 - 2.4 (any ChromoSeq that is also a MyeloSeq should have >500ng)
- Positive Controls = Yield >250ng, 260/280 = 1.4 - 2.4
- Negative Controls = Concentration <0.2ng/uL

Anything that does not meet the above conditions will need to be marked as a QC fail.

**Things to consider for a possible error handler**

- Our preferred input for library construction is 500ng. Mark any samples between 250ng and 500ng.
- Any blood or bone marrow specimen with less than 750ng should get another extraction in case we need more DNA. (Any blood or marrow that is both MyeloSeq and ChromoSeq will get another extraction if it has less than 1000ng)
- May need to come up with an "aliquot status" column during accessioning or assessment. If status = true, the yield must also be greater than the amount required for NGS and aliquot.

Thanks,
Andy

**Comment by abohanno** [comment]
[Form 5204 GPS Aliquots.xlsx](https://github.com/GTAC-MGI/GTAC-ESP-LIMS/files/15405543/Form.5204.GPS.Aliquots.xlsx)

**Comment by billtell** [comment]
Pushing current state of work to Release-15.
Remainder of work will be continued on #423

**Comment by billtell** [comment]
merged in release-15

```
Fast-forward
 content/chains/cle_wf_chain.yml                                                                           | 230 ++++++++++++++++++++++++++++++++++------------------------
 content/pipelines/cle_labkey_checkin.yml                                                                  |  15 ++++
 content/pipelines/scripts/cle_labkey_checkin.py                                                           |  42 +++++++++++
 content/pipelines/scripts/utils/Labkey.py                                                                 |  12 ++-
 content/protocols/cle_create_dilutions_protocol.yml                                                       |  65 +++++++++++++++++
 content/protocols/cle_create_pools_protocol.yml                                                           |  75 +++++++++++++++++++
 content/protocols/cle_dilutions_setup_protocol.yml                                                        | 150 ++++++++++++++++++++++++++++++++++++++
 content/protocols/{cle_extraction_reagent_lot_tracking_protocol.yml => cle_extraction_setup_protocol.yml} |   2 +-
 content/protocols/cle_kapa_aliquot_plate_protocol.yml                                                     |  38 ++++++++++
 content/protocols/cle_kapa_library_quant_ingest_protocol.yml                                              |  51 +++++++++++++
 content/protocols/cle_kapa_library_quant_results_protocol.yml                                             | 148 +++++++++++++++++++++++++++++++++++++
 content/protocols/cle_kapa_library_quantification_review_plate_setup_protocol.yml                         |  18 +++++
 content/protocols/cle_kapa_library_quantification_runsheet_protocol.yml                                   |  41 +++++++++++
 content/protocols/cle_kapa_set_well_group_protocol.yml                                                    | 126 ++++++++++++++++++++++++++++++++
 content/protocols/cle_labkey_checkin_protocol.yml                                                         | 184 ++++++++++++++++++++++++++++++++++++++++++++++
 content/protocols/cle_make_extraction_protocol.yml                                                        |  12 +++
 content/protocols/cle_pool_grouping_protocol.yml                                                          | 136 ++++++++++++++++++++++++++++++++++
 content/protocols/cle_pooling_setup_protocol.yml                                                          |  60 +++++++++++++++
 content/workflows/cle_dna_extraction_workflow.yml                                                         |  15 ++--
 content/workflows/cle_kapa_library_quantification_workflow.yml                                            |  25 +++++++
 content/workflows/cle_library_dilutions_workflow.yml                                                      |  16 ++++
 content/workflows/cle_library_pooling_workflow.yml                                                        |  19 +++++
 roles/seed/content.yaml                                                                                   |  46 ++++++++----
 23 files changed, 1408 insertions(+), 118 deletions(-)
 create mode 100644 content/pipelines/cle_labkey_checkin.yml
 create mode 100644 content/pipelines/scripts/cle_labkey_checkin.py
 create mode 100644 content/protocols/cle_create_dilutions_protocol.yml
 create mode 100644 content/protocols/cle_create_pools_protocol.yml
 create mode 100644 content/protocols/cle_dilutions_setup_protocol.yml
 rename content/protocols/{cle_extraction_reagent_lot_tracking_protocol.yml => cle_extraction_setup_protocol.yml} (98%)
 create mode 100644 content/protocols/cle_kapa_aliquot_plate_protocol.yml
 create mode 100644 content/protocols/cle_kapa_library_quant_ingest_protocol.yml
 create mode 100644 content/protocols/cle_kapa_library_quant_results_protocol.yml
 create mode 100644 content/protocols/cle_kapa_library_quantification_review_plate_setup_protocol.yml
 create mode 100644 content/protocols/cle_kapa_library_quantification_runsheet_protocol.yml
 create mode 100644 content/protocols/cle_kapa_set_well_group_protocol.yml
 create mode 100644 content/protocols/cle_labkey_checkin_protocol.yml
 create mode 100644 content/protocols/cle_make_extraction_protocol.yml
 create mode 100644 content/protocols/cle_pool_grouping_protocol.yml
 create mode 100644 content/protocols/cle_pooling_setup_protocol.yml
 create mode 100644 content/workflows/cle_kapa_library_quantification_workflow.yml
 create mode 100644 content/workflows/cle_library_dilutions_workflow.yml
 create mode 100644 content/workflows/cle_library_pooling_workflow.yml
```

**Comment by billtell** [comment]
feat merged with release-15

```
 content/pipelines/scripts/cle_specimen_assessment.py           | 161 +++++++++++++++++++++++++++++++++++++++++++++++++++--------------------------
 content/protocols/cle_extraction_setup_protocol.yml            |   5 ---
 content/protocols/cle_generate_cle_accession_data_protocol.yml |   4 +-
 content/protocols/cle_specimen_assessment_protocol.yml         |  31 +++++++++++----
 content/protocols/cle_specimen_assessment_review_protocol.yml  |   4 ++
 requirements.txt                                               |   3 +-
 6 files changed, 138 insertions(+), 70 deletions(-)
```
