### ISSUE TITLE
SC Lab: 5 v2 GEX Only Bug Fixes

### ISSUE THREAD

**Issue by LMT337** [GTAC-MGI/GTAC-ESP-LIMS#310]

**Comment by LMT337** [comment]
SC Lab: Record Service Request
Some of the information did not transfer over, like client email and cost center # (corresponds to Cost center workday)
add esp expressions
 
SC Lab: 5 prime Agilent HS 
Same as 3’, the cDNA gets run on an agilent.  Based on the concentration
Please allow for an agilent to be uploaded here, just like 3’
Add protocol col for pdf upload
 
SC Lab: 5 prime cDNA Barcode 
Changed fan out into a 1:1 because it did the same thing 3’ did
Made new experiment, additional entries went away but Child populate only brought over 1 sample, not 6.  Also did not bring over previous information
Fix populate chld sample button
 
SC Lab: 5 prime Dual SPRI Reagents
Can you make the headers say “Lot #” as well?

SC Lab: Create Library needs 2D barcode/Remaining Vol/Location col and protocol actions same as 3'
Populate child fields including sample name
Can there be a drop down of Matt’s information?  So I can choose and not have to type it in?
Jen follow up with cols/vals for picklist
 
SC Lab: Set Up Dilutions
Can “EB Lot” be changed to “EB Lot #” and autofill for all samples?
 
SC Lab: Create Dilutions
SCARY!  Samples out of order
Populate child samp button broken

**Comment by LMT337** [comment]
Index Entity sync for?: 
SC Lab: 5 prime Sample Index PCR Mix

Should this: 
SC Lab: Create Library needs 2D barcode/Remaining Vol/Location col and protocol actions same as 3'
Populate child fields including sample name
Be:
SC Lab: 5 prime cDNA Amp CleanUp Reagents

**Comment by billtell** [comment]
Can close
