### ISSUE TITLE
Seq Lab: Add check-in/check-out pipeline functions to seq Protocols

### ISSUE THREAD

**Issue by LMT337** [GTAC-MGI/GTAC-ESP-LIMS#313]
Please add the SEQ Lab: Library-Pool Pipeline Plate Check-In action to the following SEQ Lab protocols:
 
SEQ Lab: Receive Library
Insert Plate Name and Plate Barcode Columns before Next Step Column
 
SEQ Lab: KAPA Library Quantification Results
Insert Plate Name and Plate Barcode Columns before Next Step Column
 
SEQ Lab: Manual Illumina Dilutions Create Dilutions - Check In/Check Out
This protocol will generate a second entity (DIL), so there will need to be two check-in events. One for the original entity and one for the new dilution entity.
 
Insert Parent Plate Name and Parent Plate Barcode Columns after Parent ID Column
Insert Child Plate Name and Child Plate Barcode Columns after Sample Name column
 
SEQ Lab: Create Illumina Library Pools - Check in parent/child
This protocol will generate a second entity (PL), so there will need to be two check-in events. One for the original entity and one for the new pool entity.
Unfortunately, the parent names are not show in this protocol. Could rows for those be added easy enough to allow for the check-in columns?
Insert Parent Plate Name and Parent Plate Barcode Columns after 2D Barcode Column
Insert Child Plate Name and Child Plate Barcode Columns after 2D Barcode Column
 
SEQ Lab: Generate Illumina Runsheet
Insert Plate Name and Plate Barcode Columns before Next Step Column

**Comment by LMT337** [comment]
some of our workflows create new entities (dilutions or pools). this means we could be checking in the original entity along with the newly created entity. Is it possible to have something like Parent Plate Name and Child Plate Name, and the same for Well location in the same protocol

I want to be able to add location information (check-in) for both in the same protocol.

SEQ Lab: Manual Illumina Library Dilutions 29Aug2023 # 9

SEQ Lab: Manual Illumina Library Dilutions 29Aug2023 # 9
https://gtac-mgi-lims.wustl.edu/#/lims/worksheet/c1f930a2-cf99-4ea0-974a-1bcce5afc7ed

SEQ Lab: Manual Library Pooling 29Aug2023 # 8
https://gtac-mgi-lims.wustl.edu/#/lims/worksheet/ae76d9fe-98fb-4fa3-a85c-e0ae7636e5db

select well for both

Manual Illum dil create and Create Illum Lib pools
For the double pipeline.

**Comment by LMT337** [comment]
SEQ Lab: Receive Library  - Notes
Insert Plate Name and Plate Barcode Columns before Next Step Column

Adding SEQ Lab: Library-Pool Pipeline Plate Check-In Protocol to Receive Library workflow.  Recieve Library Protocol should only deal with ingest, adding more columns and another pipeline script would make this Protocol slower and possibly add more complexity to the ingest process. 

Adding plate creation option to Library-Pool Pipeline Plate Check-In Protocol to create new plate objects on ingest. 

Adding freezer check in column for freezer barcode to check plate into SEQ freezers/or Location column to select SEQ check in freezer. 

Location col is not a viable option for plate check in to freezer.

**Comment by LMT337** [comment]
Small freezers do not have shelf objects, either need to be made or just use the freezer barcode.  No way to use these barcodes as of right now. 
1b1Hih - Seq1 - Shelf 1 (542)
1b1Hin  - Seq1 - Shelf 2 (542)
1b1Hit - Seq1 - Shelf 3 (542)
1b1JIn - Seq2 - Shelf 1 (549)
1b1JIv - Seq2 - Shelf 2 (549)
1b1JID - Seq2 - Shelf 3 (549)

**Comment by LMT337** [comment]
SEQ Lab: KAPA Library Quantification Results
Insert Plate Name and Plate Barcode Columns before Next Step Column

Adding required cols for pipline check in script to work and pipeline button. Need to upgrade pipeline button script function to check into multiple plates if neccessary. 

Script updated, columns addeed to quant results protocol

**Comment by LMT337** [comment]
SEQ Lab: Generate Illumina Runsheet
Insert Plate Name and Plate Barcode Columns before Next Step Column

Conflict. This is a pipeline protocol, adding a protocol button to a pipeline protocol does not work, the pipeline set to run by the pipeline protocol overides the button and the button pipeline does not run. 

Adding plate check-in pipeline protocol to the end of the workflow instead.

**Comment by LMT337** [comment]
SEQ Lab: Manual Illumina Dilutions Create Dilutions - Check In/Check Out
This protocol will generate a second entity (DIL), so there will need to be two check-in events. One for the original entity and one for the new dilution entity.

Insert Parent Plate Name and Parent Plate Barcode Columns after Parent ID Column
Insert Child Plate Name and Child Plate Barcode Columns after Sample Name column


Wrote pipeline button script for this protocol to check in parent/dillution to plates using plate/well location.

**Comment by LMT337** [comment]
Outstanding item from this ticket: 
SEQ Lab: Create Illumina Library Pools - Check in parent/child

Need to re-vist how this would work, ESP client does not let you check items out of containers, protocol action will always remove everything from a container, not possible to check out/check in in the same protocol.

**Comment by LMT337** [comment]
Merging with release branch, MVP location solutions for this ticket will need to be reviewed by SEQ lab.  Best judgement was used to resolve/impliment these updates for MVP, with very little turn aroudn time for testing and user feedback.

**Comment by LMT337** [comment]
Add check in protocol to pool workflow.

**Comment by LMT337** [comment]
Add missing field column check to check in scripts.

**Comment by LMT337** [comment]
SEQ Lab: Illumina Setup
Update default values for 'run cycles' to 151

**Comment by LMT337** [comment]
SEQ Lab: Library-Pool Pipeline Plate Check-In
autofill on change add expression

**Comment by LMT337** [comment]
anything that gets checked in to a plate, add shelf cols.

**Comment by LMT337** [comment]
storage location for parent/child libraries need to be added to entities.

**Comment by LMT337** [comment]
Workflow: SEQ Lab: Manual Library Pooling:
Sandwich checkin protocol between workflow protocols, add check in cols/button to pool creation with them.

**Comment by tim-snyder-wustl** [comment]
Add 'Project Name' as an entity field that is updated upon ingest.

**Comment by LMT337** [comment]
{{ project_name() }} expression.
