### ISSUE TITLE
Seq Lab: DT Staging

### ISSUE THREAD

**Issue by billtell** [GTAC-MGI/GTAC-ESP-LIMS#317]
Work done prior to this ticket creation
- Create method to import smartsheet as df
-  debugged and update SEQ qc endpoint script
- write sr row to dt sheet
- qc file

work is related to #302

**Comment by billtell** [comment]
- [x] samplemap

> sample read1,read2 files will be on the same line
>column naming and order will be slightly different from previous template
>Sample Name now is Library Name to conform to previous label

- [x] Move Output Directory to SR row
- [ ] need to send a copy to analysis team for review
- [x] symlinks
- [x] instantiate working version on compute1
>may require update illumina integration with smarsheets sdk

- [ ] set up smartsheet automation on staging sheet
- [ ] need to update row for smartsheets automation to move row from staging to archive

**Comment by LMT337** [comment]
Working version with Marks Docker on compute1, Matt did have some issues running it, probably related to permissions.  Script does complete as expected. 

Holding off on automation until QC workflow finalized.

**Comment by LMT337** [comment]
- [ ] Review/Update analysis sheet
- [ ] Find rows to send to analysis
- [ ] Make analysis row
- [ ] Follow up with Paul/Erik about staging, symlink dir? 
- [ ] Move row to archive
