### ISSUE TITLE
Seq Lab: Add Project Name to Pool Ingest Libraries

### ISSUE THREAD

**Issue by LMT337** [GTAC-MGI/GTAC-ESP-LIMS#318]
Libraries made during pool ingest have no project name.  Causing downstream runsheet generation errors.  Value needs to be added to Libraries during Library creation.

**Comment by LMT337** [comment]
- [ ] Create esp query for project name
- [ ]  Add project name to Library Entity

**Comment by billtell** [comment]
this has been resolved in #354
