### ISSUE TITLE
Seq Lab: Protocol Clean-up/Pool Name for Pool Libraries/Firestore ATAC fields

### ISSUE THREAD

**Issue by tim-snyder-wustl** [GTAC-MGI/GTAC-ESP-LIMS#354]
- [x] **Workflow: SEQ Lab: KAPA Library Quantification**

SEQ Lab: KAPA Set Well Group
Hide columns:
- Freezer Location
- Plate Location
- Plate Barcode

SEQ Lab: KAPA Library Quantification Results
Hide columns: 
- Plate Name
- Plate Barcode
- Well Location
- Storage Location 
- ESP Location
- Assign Sample To Well (Button)

---

- [x] **Workflow:  SEQ Lab: Manual Illumina Library Dilutions**

SEQ Lab: Manual Illumina Dilutions Setup
Hide columns:
- Plate Barcode
- SOI
- Well Location (this should not be required field)

SEQ Lab: Manual Illumina Dilutions Create Dillutions
Hide columns:
- Parent Plate Name
- Parent Plate Barcode
- Parent Well Location
- Plate Barcode
- Plate Name
- Well Location  

**Note: Leaving Plate Barcode so child samples values can be set here if desired.  Will discuss with Matt**

---

- [x] **Workflow: SEQ Lab: Manual Library Pooling**

SEQ Lab: Pool Grouping
Hide columns: 
- Plate Barcode
- Pool Group (this should not be required field)
- Well Location (this should not be a required field)

SEQ Lab: Create Illumina Library Pools
Hide columns:
- Pool Name (this should not be a required field)
- Plate Barcode
- Plate Name
- Well Location  

**Note: Leaving Plate Barcode so child samples values can be set here if desired.  Will discuss with Matt**
**Note: Pool Name isn't a required field*

---

- [x] **Workflow: SEQ Lab: NovaSeq X Sequencing**

SEQ Lab: Illumina Setup
Hide columns:
- Freezer Location
- Plate Location
- Plate Barcode
- Pool Plate
- Pool Plate Postion
- i7 Index Sequence
- i5 Index Sequence

Update columns:
- Assay - set default to NovaSeqX 300C
- Read 1 Cycles - set default to 151
- Read 2 Cycles - set default to 151
- Sequencing Recipe - set default to 151x10x10x151

SEQ Lab: Library-Pool Pipeline Plate Check-in

This pipeline is just for pool check in and can be removed, however, the Next Step function is here. It can be moved to the previous protocol.

**Comment by billtell** [comment]
This ticket is based on this document sent from Matt.

[ESP Clean Up - LabKey Release 16Feb2024.xlsx](https://github.com/GTAC-MGI/GTAC-ESP-LIMS/files/14211188/ESP.Clean.Up.-.LabKey.Release.16Feb2024.xlsx)

**Comment by billtell** [comment]
Because so many of the storage columns are being hidden and will be unused, I'm thinking there should be an assessment of the protocol action adjustments that could/should be made.

**Comment by billtell** [comment]
@LMT337 has made modifications to the` atac_flowcell_to_firestore` function in the SEQFirestore class.

```
def atac_flowcell_to_firestore(self, parsed_data):
        for srn, library_data in parsed_data['sample_stats'].items():
            sr_doc_fs = self.get_ssr(srn)
            if not sr_doc_fs.exists:    
                srn_data_dict = dict.fromkeys(self.SR_ESP_FIELDS, 'NA')
                srn_data_dict['atac_status'] = self.atac # type: ignore
                for field in self.SR_ESP_FIELDS:
                    srn_data_dict[field] = parsed_data['srn_dict'][srn].get(field)
                self.create_ssr(srn, {**self.SR_REQUIRED_FIELDS, **srn_data_dict})
                sr_doc_fs = self.get_ssr(srn)
                self.sr_write_flowcell(parsed_data['run_stats']['flowcell_id'], parsed_data['run_stats'])
            else:
                self.db.collection(self.COLLECTION_NAME).document(srn).update({'atac_status': True})
            for esp_id, lane_dict in library_data.items():
                for lane, library_lane_data_dict in lane_dict.items():
                    for idx, library_lane_data in library_lane_data_dict.items():
                        library_lane_data.update({'abs_date': self.abs_date,'date': self.datestamp, 'demux_id': self.demux_id})
                        if idx == 'fastq_files':
                            library_lane_data.update({'esp_id': esp_id, 'flowcell_id': parsed_data['run_stats']['flowcell_id'], 'lane': lane})
                            self.sr_write_library(srn, esp_id, library_lane_data)
                            continue
                        library_lane_data['fail'] = False
                        self.sr_write_library(srn, esp_id, library_lane_data)
```

- updates atac_status to true if it already exists
- adds lane number to atac fastq_files doc

**Comment by billtell** [comment]
Adding `Pool Name` to `CRM_ESP_LIBRARY_HEADER_MAPPING` in the receive_library_pools pipeline script.
This should link the Pool Name to the libraries contained in that pool.
this should address the issue described in #318

**Comment by billtell** [comment]
adding this onrender function to the LabKey checkin protocol to display Pool Name or Sample Name depending on ingest.
```
function onrender_SampleName_or_PoolName(api) {
	let lib_ingest = ['SEQ Lab: Receive Library'];
	let pool_ingest = ['SEQ Lab: Receive Library Pools'];
	const workflow_name = api.getWorkflowName();
	if (lib_ingest.includes(workflow_name)) {
		api.hideColumns(['Pool Name']);
	}
	if (pool_ingest.includes(workflow_name)) {
		api.hideColumns(['Sample Name']);
	}
}
```
Because both libraries and pools could be going through pooling/dilutions workflow, leaving both visible.

**Comment by billtell** [comment]
after some reconsideration, moving to the following async function to hide a column if all of 1 or the other are present:
```
async function onrender_SampleName_or_PoolName(api) {
	let lib_ingest = ['SEQ Lab: Receive Library'];
	let pool_ingest = ['SEQ Lab: Receive Library Pools'];
	let pool_or_dil = ['SEQ Lab: Manual Library Pooling', 'SEQ Lab: Manual Illumina Library Dilutions'];
	const workflow_name = api.getWorkflowName();
	if (lib_ingest.includes(workflow_name)) {
		api.hideColumns(['Pool Name']);
	}
	if (pool_ingest.includes(workflow_name)) {
		api.hideColumns(['Sample Name']);
	}
	if (pool_or_dil.includes(workflow_name)) {
		const sample_uuids = api.getSampleUuids();
		const samples = await fetch(`/api/samples?uuids=${JSON.stringify(sample_uuids)}`)
			.then(res => res.json())
			.catch(err => console.error(err)); 
		let lib = false;
		let pool = false;
		samples.forEach(sample => {
			if (sample.name.includes('LIB')) {
				lib = true;
			}
			if (sample.name.includes('PL')) {
				pool = true;
			}
		}
		);
		debugger;
		if (!lib && pool) {
			api.hideColumns(['Sample Name']);
		}
		if (lib && !pool) {
			api.hideColumns(['Pool Name']);
		}
	}
}
```

**Comment by billtell** [comment]
```
 git merge gtac/feat-354
Updating 5826ae08..8166ed7b
Fast-forward
 content/pipelines/scripts/seq_qc_firestore.py                                 |  3 ---
 content/pipelines/scripts/seq_receive_library_pools.py                        |  3 +++
 content/pipelines/scripts/utils/Labkey.py                                     | 12 ++++++------
 content/protocols/seq_generate_illumina_runsheet_protocol.yml                 |  9 ++++++++-
 content/protocols/seq_illumina_setup_protocol.yml                             | 13 +++++++++++--
 content/protocols/seq_kapa_library_quantification_results_protocol.yml        |  6 ++++++
 content/protocols/seq_kapa_set_well_group_protocol.yml                        |  3 +++
 content/protocols/seq_labkey_checkin.yml                                      | 37 +++++++++++++++++++------------------
 content/protocols/seq_manual_illumina_dilutions_create_dilutions_protocol.yml |  3 +++
 content/protocols/seq_manual_illumina_dilutions_setup_protocol.yml            |  4 +++-
 content/protocols/seq_pool_grouping_protocol.yml                              |  5 +++--
 content/workflows/seq_novaseq_x_sequencing_workflow.yml                       |  3 ---
 extensions/client/invokables.js                                               | 42 +++++++++++++++++++++++++++++++++++++-----
 extensions/server/SeqFirestoreQC.py                                           |  8 +++++---
 extensions/server/invokables.py                                               | 10 +++++-----
 15 files changed, 112 insertions(+), 49 deletions(-)
```
