### ISSUE TITLE
SC Lab: New 3' Workflow Chain

### ISSUE THREAD

**Issue by tim-snyder-wustl** [GTAC-MGI/GTAC-ESP-LIMS#369]
Refactor current SC workflow chain nodes into a new 3' workflow chain.

**Comment by billtell** [comment]
**First revised wf chain review feedback**:

- [x] Existing cDNA Node: Sample protocol to make 10ul aliquot - connect to 3P GEX LC
- [x] add flowlines from 3P cDNA to GEX and GEX to 3P cDNA
- [x] make dilution node startable
- [x] make cDNA protocol fan-out
- [x] cDNA- entity value: Feature -> Feature Sup
- [x] Rename nodes from 3P to 3Prime
- [x] Remove dupicate Sample Notes from cDNA entity
- [x] Add Next step to existing cDNA sample protocol

**Comment by billtell** [comment]
![Image](https://github.com/GTAC-MGI/GTAC-ESP-LIMS/assets/106331436/833c6ee7-18df-4bbe-965f-ff681919d307)

**Comment by billtell** [comment]
- [x] Export workflow chain yaml
- [x] Export cDNA, Feature LC and GEX LC workflow yaml
- [x] add to content.yml

**Comment by billtell** [comment]
- [x] clean up 3' duplicate protocols:  `'SC Lab: 3 prime Qubit and Agilent 2'`

**Comment by billtell** [comment]
- [x] make sure `Next Step` columns are added to the last protocol of every workflow

**Comment by billtell** [comment]
- [ ] Remaining Volume tracking?
