### ISSUE TITLE
Seq Lab: Clean up fields requested by techs

### ISSUE THREAD

**Issue by tim-snyder-wustl** [GTAC-MGI/GTAC-ESP-LIMS#372]
[Uneeded Columns for Lab Techs.xlsx](https://github.com/GTAC-MGI/GTAC-ESP-LIMS/files/14528899/Uneeded.Columns.for.Lab.Techs.xlsx)

**Comment by billtell** [comment]
unhide the `BC Check` column in the manual dilutions workflow
