### ISSUE TITLE
SC Lab: Remaining Volume Tracking - 3' workflow

### ISSUE THREAD

**Issue by billtell** [GTAC-MGI/GTAC-ESP-LIMS#377]
- update cDNA and cDNA aliquot Remaining Volume values
- need to update previous library after workflow transitions!

For 3' the volume transfers happen at the following steps:

**SC Lab: 3 Prime GEX LC --> SC Lab dilutions**
This is a volume transfer but it is variable passed on the final concentration of the library. What we have set up in ESP in the dilution tab tells us the volume to transfer. The remaining library that is not diluted goes in the freezer until it is needed again or when it's time to toss for good.

**SC Lab: 3 Prime cDNA --> SC Lab Aliquot --> SC Lab: 3 Prime GEX LC**
This is a 10ul transfer. The 3' cDNA ends with 40ul, we then aliquot out 10ul and the remaining 30ul goes in the freezer until it is needed again or when it's time to toss for good.

**SC Lab: 3 Prime cDNA --> SC Lab Aliquot --> SC Lab: 3 Prime Feature LC**
This is a 5ul aliquot transfer into library construction, most of the time. Sometimes it can be 10ul if we need to add more to the reaction. The remaining feature supernatant goes in the freezer until it is needed again or when it's time to toss for good.

**SC Lab: 3 Prime Feature LC --> SC Lab dilutions**
This is a volume transfer but it is variable passed on the final concentration of the library. What we have set up in ESP in the dilution tab tells us the volume to transfer. The remaining library that is not diluted goes in the freezer until it is needed again or when it's time to toss for good.

**Comment by billtell** [comment]
From #363 :
- [ ] - [ ] Remove 2D barcode from Qubit and Agilent protocols - Remaining volume expression needs to be fixed, hide storage location

**Comment by billtell** [comment]
Email from Jen:

For 3’ the volume transfers happen at the following steps.
 
SC Lab: 3 Prime cDNA à SC Lab Aliquot à SC Lab: 3 Prime GEX LC – This is a 10ul transfer.  The 3’ cDNA ends with 40ul, we then aliquot out 10ul and the remaining 30ul goes in the freezer until it is needed again or when it’s time to toss for good.
 
SC Lab: 3 Prime GEX LC à SC Lab dilutions.  This is a volume transfer but it is variable passed on the final concentration of the library.   What we have set up in ESP in the dilution tab tells us the volume to transfer.  The remaining library that is not diluted goes in the freezer until it is needed again or when it’s time to toss for good.
 
SC Lab: 3 Prime cDNA à SC Lab Aliquot à SC Lab: 3 Prime Feature LC – This is a 5ul aliquot transfer into library construction, most of the time.  😊  Sometimes it can be 10ul if we need to add more to the reaction. The remaining feature supernatant goes in the freezer until it is needed again or when it’s time to toss for good.
 
SC Lab: 3 Prime Feature LC à SC Lab dilutions.  - This is a volume transfer but it is variable passed on the final concentration of the library.   What we have set up in ESP in the dilution tab tells us the volume to transfer.  The remaining library that is not diluted goes in the freezer until it is needed again or when it’s time to toss for good.

**Comment by tim-snyder-wustl** [comment]
Need to add `Volume to Use` column in each setup protocol, that value will decrement `Remaining Volume`.

**Comment by tim-snyder-wustl** [comment]
Clarification from Jen for SC Lab: 3 Prime Feature LC --> SC Lab dilutions:

> The feature sup is 40ul, when we take that into aliquot, we take 5ul of that to make go into 3 Prime Feature LC.  So the Feature sup would then be 35ul. When the feature library is made that final library is also 40ul, so based on the final concentration, the volume will be variable for a dilution aliquot.
