### ISSUE TITLE
SC Lab: Aliquot node

### ISSUE THREAD

**Issue by billtell** [GTAC-MGI/GTAC-ESP-LIMS#378]
Change Existing cDNA node in all workflows to a single Aliquot node that creates a `cDNA Aliquot` entity.
In the first protocol, the user can select the number of Aliquots to make in the following, fan-out sample protocol.

**Comment by billtell** [comment]
- [x] Delete Existing cDNA in 3'
- [x] Delete  Existing cDNA in 5'
- [x] Delete  Existing cDNA in Multiome
- [x] Make SC Lab: Aliquot node
- [x] Make fan-out dynamic in the sample protocol

**Comment by billtell** [comment]
- [x] Connect accessioning node to aliquot
- [x] Type in quantity

**Comment by billtell** [comment]
- [x] Aliquot Node will make aliquot entity type that is being added
>  need to update once complete

this is being done on #382

**Comment by LMT337** [comment]
#382 complete.
