### ISSUE TITLE
CLE Lab: Copy Seq nodes to CLE wf chain

### ISSUE THREAD

**Issue by tim-snyder-wustl** [GTAC-MGI/GTAC-ESP-LIMS#397]
Make a *copy* of these nodes from the Seq WF Chain.

- Attach Dilutions Node, after Capture and Library Construction

- Attach KAPA qPCR node to Capture, Whole Genome Library Construction, set before Send to Seq node.

Here's the Seq Lab workflow:

http://sandbox5.wucon.wustl.edu:11702/#/master/workflow-chains/details/89782d5e-ba4a-4b1e-9e6b-e71c7d166f68/workflow/9df23e9f-eaf5-4a4c-8282-be8dd3613c0f

![Image](https://github.com/GTAC-MGI/GTAC-ESP-LIMS/assets/91081406/048c67ad-06b8-4964-8fa4-1922ac5903c7)

*Note*

Leave the pipeline scripts as placeholders, will probably want to replace them to work with EpMotion instead of Janus.

**Comment by billtell** [comment]
- [x] SEQ Lab: Pool Grouping
- [x] SEQ Lab: Illumina Library Pooling Setup
- [x] SEQ Lab: Create Illumina Library Pools
- [x] CLE Lab: LabKey Check-In

**Comment by billtell** [comment]
- [x] SEQ Lab: Illumina Dilutions Setup
- [x] SEQ Lab: Illumina Dilutions Create Dilutions
- [x] CLE Lab: LabKey Check-In

**Comment by billtell** [comment]
- [x] SEQ Lab: KAPA Set Well Group
- [x] SEQ Lab: KAPA Aliquot Plate
- [x] SEQ Lab: KAPA Library Quantification Review Plate Setup
- [x] SEQ Lab: KAPA Library Quantification Runsheet 
- [x] SEQ Lab: KAPA Library Quant Ingest
- [x] SEQ Lab: KAPA Library Quantification ResultS

**Comment by billtell** [comment]
- [x] Add new cle protocols to `content.yml`
- [x] combine into workflows
- [x] export workflow yml

**Comment by billtell** [comment]
Workflow Chain reconfigured

- [x]  Nodes added for SEQ wf
- CLE Lab: Library Dilutions
- CLE Lab: Library Pooling
- CLE Lab: KAPA Library Quantification

![Image](https://github.com/GTAC-MGI/GTAC-ESP-LIMS/assets/106331436/d75c3eba-752c-41ad-b64c-8066adc677b4)

**Comment by billtell** [comment]
![Image](https://github.com/GTAC-MGI/GTAC-ESP-LIMS/assets/106331436/4938efcd-3ddc-484b-9e5f-3ac3753457cb)

**Comment by billtell** [comment]
- A placeholder sample protocol was added to `CLE Lab: DNA Extraction` wf
