### ISSUE TITLE
Library Prep Choice Workflow

### ISSUE THREAD

**Issue by tim-snyder-wustl** [GTAC-MGI/GTAC-ESP-LIMS#40]
The library prep types and their sub-types are:

- 3'v3.1 GEX with Feature, TotalSeqA - existing cDNA
- 3'v3.1 GEX with Feature,  TotalSeqB - existing cDNA
- 3'v3.1 GEX with Feature,  CellPlex
- 3'v3.1 GEX with Feature,  CRISPR

---

- 5'v2 GEX only
- 5'v2 GEX with 1 Enrichment (TCR or BCR)
- 5'v2 GEX with 2 Enrichment  (TCR and BCR)
- 5'v2 GEX with 1 Enrichment  (TCR or BCR) with Feature, TotalSeqC
- 5'v2 GEX with 2 Enrichments  (TCR and BCR) with Feature, TotalSeqC
- 5'v2 GEX with Feature,  TotalSeqC
- 5'v2 GEX only - existing cDNA
- 5'v2 GEX with 1 Enrichment  (TCR or BCR) - existing cDNA
- 5'v2 GEX with 2 Enrichment  (TCR and BCR) - existing cDNA
- 5'v2 GEX with 1 Enrichment  (TCR or BCR) with Feature, TotalSeqC - existing cDNA
- 5'v2 GEX with 2 Enrichments  (TCR and BCR) with Feature, TotalSeqC - existing cDNA
- 5'v2 GEX with Feature,  TotalSeqC - existing cDNA

---

- Multiome 3'v3.1 and ATAC
- Multiome 3'v3.1 and ATAC -  existing cDNA

**Comment by LMT337** [comment]
Integrate into accessioning i.e workflow prep is assigned here.

**Comment by tim-snyder-wustl** [comment]
Closing. 

Adding functionality here: https://github.com/GTAC-MGI/GTAC-ESP-LIMS/issues/16
