### ISSUE TITLE
Seq Lab: Pool Molarity

### ISSUE THREAD

**Issue by tim-snyder-wustl** [GTAC-MGI/GTAC-ESP-LIMS#404]
In Illumina Set Up protocol: Pool molarity not being pulled through sometimes - assessed concentration from qPCR, or dilution molarity if its a dilution.

**Comment by tim-snyder-wustl** [comment]
@mcordes-gtac do I have the above notes correct for qPCR? 

These are the relevant fields in the KAPA Quantification Results protocol:

```
    - "Average Concentration (ng/µl)":
        name: "Average Concentration (ng/µl)"
        read_only: true
        rule: numeric
    - Average Library Size (bp):
        name: Average Library Size (bp)
        read_only: true
        rule: numeric
        value: "{{ entity_value('Average Library Size (bp)') }}"
    - Size Adjusted Concentration (pM):
        name: Size Adjusted Concentration (pM)
        read_only: true
        rule: numeric
        value: "{{ float (cell ('Average Concentration (ng/µl)')) * 452 / float(cell('Average Library Size (bp)'))\
          \ }}"
    - Molarity (nM):
        name: Molarity (nM)
        rule: numeric
        value: "{{ float(cell('Size Adjusted Concentration (pM)')) / 1000 }}"
```

**Comment by mcordes-gtac** [comment]
Yes, sorry Tim.  These appears to be correct. This would apply to any entity, correct? Library, library dilution, pool, pool dilution?

Thanks,
Matt

**Comment by tim-snyder-wustl** [comment]
So, dumb question @mcordes-gtac 

In the Illumina Setup Protocol, Pool Molarity is defined like this:

```
    - Pool Molarity (nM):
        rule: numeric
        value: "{{ entity_value('Assessed Molarity (nM)') or '' }}"
```

where the value is the entity property `Assessed Molarity (nM)` or blank if that property is empty.

When going through the KAPA quant protocol, which of the above fields should map to the `Assessed Molarity (nM)` entity field?

**Comment by mcordes-gtac** [comment]
@tim-snyder-wustl Not sure which protocol you are referring to, there are several KAPA quant XXX protocols in that worksheet.

**Comment by tim-snyder-wustl** [comment]
@mcordes-gtac sorry, the KAPA Quantification Results protocol (the last one in the workflow):

http://sandbox5.wucon.wustl.edu:11702/#/master/workflow-chains/details/89782d5e-ba4a-4b1e-9e6b-e71c7d166f68/workflow/9df23e9f-eaf5-4a4c-8282-be8dd3613c0f

**Comment by mcordes-gtac** [comment]
The Assessed Molarity (nM) entity field would get updated from column _Molarity (nM)_ which is the calculated value in that protocol.
