### ISSUE TITLE
CLE Lab: Custom entity types and ESP IDs

### ISSUE THREAD

**Issue by tim-snyder-wustl** [GTAC-MGI/GTAC-ESP-LIMS#408]
ESP Sequence:

```
asscession-num-specimen-type-06
```

- Prefix entity type names with `CLE-`
- Look in to entity type classes for inheritance

**Comment by abohanno** [comment]
[CLE Custom ESP Entity Types.docx](https://github.com/GTAC-MGI/GTAC-ESP-LIMS/files/15502343/CLE.Custom.ESP.Entity.Types.docx)

**Comment by abohanno** [comment]
box link for CLE custom entity types:
https://wustl.app.box.com/file/1549608469404

**Comment by tim-snyder-wustl** [comment]
@abohanno  For these new entities, are there any properties that are *not* required?

And are any of them values that are a fixed selection, meaning they could be a dropdown instead of a plain text field?

**Comment by tim-snyder-wustl** [comment]
@abohanno I've added a Cost Center property to each new entity so we can run reports on that, but we'll need to tag samples with that info as well at accessioning.
