### ISSUE TITLE
Create Storage Containers For Samples

### ISSUE THREAD

**Issue by LMT337** [GTAC-MGI/GTAC-ESP-LIMS#45]
3' & 5' DNA and Libraries will need barcoded storage containers:

CDNA AMP AND CLEANUP
1.7ml tubes
96 nunc box, record well location

FEATURE LIBRARY
2d tubes
96 plate, record well location

GENE EXPRESSION LIBRARY
2d tubes
96 plate, record well location

ENRICHMENT LIBRARY
2d tubes
96 plate, record well location

ENRICHMENT
1.7ml tubes
96 nunc box, record well location

**Comment by tim-snyder-wustl** [comment]
- cNDA, enrichments, and feature sup - 1.7 mL tubes, checked into nunc box (IC0) and position is selected
- Libraries - checked into 2D plate (2D tubes) by position. Each plate has an RJ barcode on it.

<img width="1338" alt="freezer-storage-notes" src="https://user-images.githubusercontent.com/91081406/160432390-bb32d8ce-a602-45c1-a69d-ab296b3a41c1.png">
