### ISSUE TITLE
CLE Lab: Pipeline script to trim ingest sheet

### ISSUE THREAD

**Issue by tim-snyder-wustl** [GTAC-MGI/GTAC-ESP-LIMS#450]
For CLE, ingest will compose of two steps.

1. Trim a CSV ingest file down to only samples listed that do not currently exists.
2. Do the actual ingest with the newly created trimmed-down list.

This ticket is for part 1.

How this will be done is TBD.

To be done before https://github.com/GTAC-MGI/GTAC-ESP-LIMS/issues/451

**Comment by tim-snyder-wustl** [comment]
Implement this as a stand-alone pipeline script.

Waiting on a sample file from @abohanno

**Comment by abohanno** [comment]
Hi Guys,

I do not have an update on the log file that would be delivered for GPS assays (SOMA and IDT Germline Exome). We plan to discuss this with Dr. Spencer at the next meeting. Hopefully I will have an update afterwards for our next meeting. In the meantime, we're working off the assumption that it will be structured very similarly to the MyeloSeq log. I have attached an example file with the column headers and what info they indicate. Any column header without an explanation is most likely unnecessary for our ingest purposes.

[CLE_Ingest_Template.xlsx](https://github.com/user-attachments/files/16874240/CLE_Ingest_Template.xlsx)

Andy

**Comment by abohanno** [comment]
I don't want to get anyone's hopes up, but the CoPath dashboard may have a functionality of filtering this for us based upon samples that were newly accessioned/received. Once I am more familiar with what this looks like we can address this again. There is a chance we won't need to work on this!
