### ISSUE TITLE
SC Barcoding

### ISSUE THREAD

**Issue by LMT337** [GTAC-MGI/GTAC-ESP-LIMS#46]
There are steps in SC that will require initial barcoding (printing of barcodes, linking to samples) and steps that will need to link exisiting barcodes to new tubes (print barcodes for new tubes).  There is an existing BC naming format for each step, if possible, preserve that naming convention but if a new format is required, it's not a problem.

**Comment by tim-snyder-wustl** [comment]
Notes:

- One barcode per plate
- Scans happen on a per-shelf basis.
- XT barcodes are used for accessioning, then to the 4-8 barcode. uses a 1-to-1 relationship.
- 4H barcodes are attached to dilution libraries.
- Visionmate scans entire tray of 2d tubes. will then translate 'external' barcodes to an internal barcode format.
- Visionmate also checks (assigns well positions) multiple 2D tubes into plates

Barcodes needed for:

Dillution - The final diluted library is linked to this new dilution tube which is sent to qPCR.  The final library is then stored in the freezer. Library barcode to Dilution barcode. 10nM dilutions are the children of library barcodes. This dilution will need to be checked into the freezer system in qPCR and then be able to be accepted into qPCR. These dilution library barcodes are currently known as '4H' barcodes.

---

1. Accessioning provides source barcdode (XT) WO creation
2. Linking (either / or):
    - XT (parent) gets link to aliquot (3y) for cDNA and storage
    - XT (parent) gets linked to 48 barcode for libraries
        - picklist of library type (all)
        - index selection
        - volume
        - concentration

- 48 barcode can go to qPCR or be linked to 4H dilution.
- Both barcodes need Funding and WO?  

---

<img width="1322" alt="barcoding-notes" src="https://user-images.githubusercontent.com/91081406/160432112-41745744-609f-4b53-8eb8-514947653359.png">

**Comment by LMT337** [comment]
Completing with https://github.com/GTAC-MGI/GTAC-ESP-LIMS/issues/56
