### ISSUE TITLE
CLE Lab: Sample protocols should create new CLE entities

### ISSUE THREAD

**Issue by tim-snyder-wustl** [GTAC-MGI/GTAC-ESP-LIMS#470]
Change CLE Sample Protocols to use CLE entities

**Comment by billtell** [comment]
- [x] 'CLE Lab: Create Dilutions' -> CLE Library Dilution
- [x] 'CLE Lab: Create Library Pools' -> CLE Sequencing Pool
- [x] 'CLE Lab: EpMotion Dilution Setup' -> CLE Library Dilution
- [ ] 'CLE Lab: EpMotion Pooling Setup'
- [x] 'CLE Lab: ILMN Library Construction' -> CLE Library
- [x] 'CLE Lab: KAPA Hyper Library Construction' -> CLE Library
- [x] 'CLE Lab: DNA Extraction' -> CLE Genomic DNA
- [x] 'CLE Lab: Targeted Capture Pooling' -> CLE Library Capture Pool
- [ ] 'CLE Lab: Targeted Capture'

**Comment by billtell** [comment]
### CLE Entities 
- CLE Specimen
- CLE Genomic DNA
- CLE Library
- CLE Library Dilution
- CLE Library Capture Pool
- CLE qPCR Dilution
- CLE Sequencing Dilution
- CLE Sequencing Pool

**Comment by billtell** [comment]
Need DNA Dilution
