### ISSUE TITLE
qPCR values not retained at "Library Pooling" for samples that did not receive a dilution

### ISSUE THREAD

**Issue by tim-snyder-wustl** [GTAC-MGI/GTAC-ESP-LIMS#62]
Worksheet: Library Pooling 3March2022 Set1

Need most recent qPCR value to have priority.

Example:
Worksheet Library Pooling 3March2022 Set1 - LIB000192, LIB000202 and LIB000205 reverted to original molarity

set samples to retain (update) qPCR values

**Comment by tim-snyder-wustl** [comment]
Workflow: Details for SEQ Lab: Manual Library Pooling
Protocol: SEQ Lab: Pool Grouping

---

qPCR Workflow: SEQ Lab: KAPA Library Quantification
qPCR Protocol: KAPA Library Quantification Results

---

![Image](https://user-images.githubusercontent.com/91081406/175602493-c3f1d02e-c762-43af-8d5b-9e0ddb42d4f5.png)

**Comment by tim-snyder-wustl** [comment]
Waiting on clarification from Matt.

**Comment by tim-snyder-wustl** [comment]
**Trying to clarify the issue.**

Verify that this is what is needed:

---
 
The results from this KAPA Results protocol:
 
https://gtac-mgi-lims.wustl.edu/#/builders/protocols/details/1c63e3fe-6be7-4e4b-8205-1fb953019c6e
 
to be saved in the Illumina Library entity:
 
https://gtac-mgi-lims.wustl.edu/#/builders/entity-types/details/482ff0d1-6ee6-41a9-826f-67ff090f1fde
 
and those results should be visible in the Pool Grouping protocol:
 
https://gtac-mgi-lims.wustl.edu/#/builders/protocols/details/494d2548-817e-4855-8a4e-228b1aa8f148
 
What values in the Pool Grouping protocol map to values in the Illumina Library entity?

**Comment by mcordes-gtac** [comment]
This mapping is accurate.  Illumina Library "Molarity (nM)" = Pool Grouping "Library Molarity (nM)"

Thanks,
Matt

**Comment by tim-snyder-wustl** [comment]
@mcordes-gtac is it ok to rename the worksheet value from "Library Molarity (nM)" to simply "Molarity (nM)" for the sake of clarity or is there not enough context for that?

**Comment by mcordes-gtac** [comment]
That is perfectly fine, I think.  The entity itself defines what it is (library, pool or dilution) so this could be universal across all of those.

**Comment by tim-snyder-wustl** [comment]
Sorry, @mcordes-gtac Is the KAPA Results protocol the correct place to save values to the Library entity though?

https://gtac-mgi-lims.wustl.edu/#/builders/protocols/details/1c63e3fe-6be7-4e4b-8205-1fb953019c6e

There are no fields there for molarity or volume.

**Comment by mcordes-gtac** [comment]
Yeah, that needs to be updated to standardize the naming.  Right now it is Concentration (nM)... that should be Molarity.

**Comment by tim-snyder-wustl** [comment]
@mcordes-gtac is that the only value you need saved?

**Comment by mcordes-gtac** [comment]
Yes, for this protocol, the Molarity will be updated based on qPCR results.  Volume should be updated as well automatically based on the consumed setting, correct?  Must of this was developed upfront from L7 and they did say the consumed volume for qPCR was set at 2uL.  That should be reflected.

**Comment by tim-snyder-wustl** [comment]
@mcordes-gtac When you say 'updated' do you mean the value of Molarity and Volume should be saved to the Library Entity? That's what I'm referring to. Or for volume are you meaning the values in the worksheet should get automatically updated?

For the Pool Grouping protocol:

- when 'Volume to add in Pool (μL)' is changed, 'Remaining Volume (μL)' and 'Total Pool Volume (μL)' are updated automatically.
- when 'Total Pool Volume (μL)' is changed, 'Pool Molarity (nM)' is updated automatically.

I'm not sure where 'Consumed Volume' comes from and I'm not seeing any reference to 2µL (or any variation of) in the code.

**Comment by tim-snyder-wustl** [comment]
*Note*

Need to also make sure groupings are applied in the KAPA protocols.


![Image](https://user-images.githubusercontent.com/91081406/179062252-405f5f45-3dc2-44c2-9552-a329eb946a1d.png)
