### ISSUE TITLE
Pooled library information is not autopopulated in the worksheet after pooling

### ISSUE THREAD

**Issue by tim-snyder-wustl** [GTAC-MGI/GTAC-ESP-LIMS#63]
Worksheet: Library Pooling 3March2022 Set1

Pool size (number of samples in pool) - pool molarity, pool volume should be autopopulated.  Would be good to see underlying libraries in the pool here along with individual sample attributes

**Comment by LMT337** [comment]
Worksheet link: 
https://gtac-mgi-lims.wustl.edu/#/lims/worksheet/6d22d9fc-5638-4914-918a-c6eb38ad97a8

**Comment by LMT337** [comment]
In addition, updated column names in accesioning protocols to work with entity updates.  Synced updated columns to the entity. Fixed broken ESP expressions.  Fixed broken onChange() functions and typos in functions.  

Underlying libraries will need to be a post mvp feature addition.
