### ISSUE TITLE
Add sample barcode column to dilution protocols

### ISSUE THREAD

**Issue by tim-snyder-wustl** [GTAC-MGI/GTAC-ESP-LIMS#65]
Add sample barcode column to Manual Dilution worksheet protocols Manual Dilution and Create Dilution.

Manual Library Dilution Workflow: 
https://gtac-mgi-lims.wustl.edu/#/builders/workflows/details/b5d4d0b1-bdaa-43ca-97eb-6f9e94dc21f7

2D barcodes for 2D tubes

Protocols:
- Manual Dilutions 
- Create Dilutions

**Comment by tim-snyder-wustl** [comment]
Is the barcode automatically generated from the GTAC ID? Will need to investigate more.

**Comment by tim-snyder-wustl** [comment]
Populate worksheet with a scannable barcode on a plate. Need to confirm what is in plate is in ESP and vice versa. Create a new plate-check protocol? Need to investigate further on how to implement.

**Comment by LMT337** [comment]
Talked to Matt, SEQ is going to update this workflow.

**Comment by tim-snyder-wustl** [comment]
- The new `SEQ Lab: Manual Illumina Library Dilutions` workflow will replace `SEQ Lab: Manual Library Dilution` 
- Need to add a new button to autopopulate fields in new dilutions sample protocol (since ESP will not let you set default values for sample protocols) in `SEQ Lab: Manual Illumina Dilutions Create Dilutions`. 
- `Remaining Volume` field corresponds to `Normalized Volume` in previous protocol. `Molarity` corresponds to `Normalized Molarity` in previous protocol.
- Be sure to check that changes here do not have a ripple effect and impact or break things further downstream.
