### ISSUE TITLE
Runsheets for Janus Library Pool

### ISSUE THREAD

**Issue by tim-snyder-wustl** [GTAC-MGI/GTAC-ESP-LIMS#66]
Worksheet: Janus Dilutions 9March2022

Need to generate a Janus Runsheet for dilutions based on provided template

Workflows:
- Janus Library Dilutions
- Janus Library Pool

Need to integrate ESP and Janus hardware if possible, otherwise you can import CSV from Janus terminal.

**Comment by mcordes-gtac** [comment]
[example-janus-dilution.csv](https://github.com/GTAC-MGI/GTAC-ESP-LIMS/files/8718550/example-janus-dilution.csv)
[example-janus-pool.csv](https://github.com/GTAC-MGI/GTAC-ESP-LIMS/files/8718551/example-janus-pool.csv)

**Comment by tim-snyder-wustl** [comment]
It looks like there is already a Janus Runsheet pipeline script?
Script: https://gtac-mgi-lims.wustl.edu/#/analysis/pipelines/details/5f8670e7-a327-4f55-a30a-e19338eb6481
Instance: https://gtac-mgi-lims.wustl.edu/#/analysis/monitor/details/de0a7d3c-54f3-453e-af10-7b94e18e2303
Does it need to be updated to look like the provided CSVs here?

Where does the data for this runsheet come from? Which protocol, which values? Are there any calculations? Any protocol / worksheet with real-world values as an example data set would be helpful.

Need more detail.
