### ISSUE TITLE
KAPA qPCR Validation protocol

### ISSUE THREAD

**Issue by tim-snyder-wustl** [GTAC-MGI/GTAC-ESP-LIMS#67]
Provide a new protocol for qPCR that allows evaluation of the raw qPCR output file in order to eliminate out of range readings from the final molar calculations.

Lightcycler results:

- 3 values for each sample
- validate to remove bad readings

Need ESP to ingest lightcycler results, user manually reviews results in ESP, chooses what samples to move forward and what samples to drop from the experiment.

**Comment by tim-snyder-wustl** [comment]
A full-on user story would be helpful in understanding here.

Where should this new protocol be placed within the Workflow Chain? What are the inputs, is it just molarity? Is this data that comes from the Lightcycler? Is it a CSV that is uploaded? What is the formula for readings out of range? What is the range? Does this mean there should be a Pass/Fail Status column? What does 'remove the bad readings' mean? Does that mean the results are loaded in to a worksheet and then samples can be failed, and others can continue downstream?

**Comment by tim-snyder-wustl** [comment]
Remove results from triplicates - in KAPA Quant workflow, after the results have been ingested. We can automate the generation of a pass / fail flag if needed, just need to know the required range. From there in the worksheet samples can be failed or passed along downstream.

**Comment by mcordes-gtac** [comment]
@tim-snyder-wustl any of the triplicate values should be flagged if they are **>0.5nM +/-** any other triplicate values.

**Comment by tim-snyder-wustl** [comment]
@mcordes-gtac Do you want this check to be in the KAPA Library Quantification Results protocol [https://gtac-mgi-lims.wustl.edu/#/builders/protocols/details/1c63e3fe-6be7-4e4b-8205-1fb953019c6e] or should it be its own protocol that follows the Results?

**Comment by mcordes-gtac** [comment]
@tim-snyder-wustl This should be its own protocol before the Results.

**Comment by tim-snyder-wustl** [comment]
@mcordes-gtac Sorry, I need more clarification on this. 

Where are the triplicates calculated and shown? You need to be able to fail a triplicate sample if its molarity is 0.5 nM above or below its siblings, correct? I'm not seeing where this evaluation should happen.

**Comment by mcordes-gtac** [comment]
@tim-snyder-wustl The triplicates are part of the .qpc file saved from the Roche LightCycler instrument.  The same file that is ingested at _KAPA Library Quant Ingest_ .  The current LIMS provides each value with the option to toggle yes or no to keep the value as part of the final calculated molarity.  The standard is 0.5nM above or below.

**Comment by tim-snyder-wustl** [comment]
Ok, so to be clear, you need a new protocol that shows what's in the .qpc file where you can pass / fail samples based on *concentration*? That's what the column name is in the file. Do you want to see the other values as well?

```
Experiment: 5b0013I_AB_11420  Selected Filter: SYBR Green I / HRM Dye (465-510)
Include	Color	Pos	Name	Cp	Concentration	Standard	Status
True	255	A1	Sample 1	12.11	3.64E0	0	
True	255	A2	Sample 2	12.15	3.56E0	0	
True	255	A3	Sample 3	12.13	3.60E0	0	
True	255	A4	Sample 4			0
True	255	A5	Sample 5			0
True	255	A6	Sample 6			0
True	255	A7	Sample 7			0
True	255	A8	Sample 8			0	
True	255	A9	Sample 9			0
True	65280	A10	Sample 10			0	
True	65280	A11	Sample 11			0	
True	65280	A12	Sample 12			0	
True	65280	A13	Sample 13			0	
True	65280	A14	Sample 14			0	
True	65280	A15	Sample 15			0	
True	65280	A16	Sample 16			0	
True	65280	A17	Sample 17			0	
True	65280	A18	Sample 18			0	
True	128	A19	Sample 19	  9.65	1.75E1	20	
True	128	A20	Sample 20	  9.48	1.95E1	20	
True	128	A21	Sample 21	  9.49	1.94E1	20	
True	65280	A22	Sample 22			0	
True	65280	A23	Sample 23			0	
True	65280	A24	Sample 24			0	
True	65280	B1	Sample 25			0	
True	65280	B2	Sample 26			0	
```

**Comment by mcordes-gtac** [comment]
I think what I would like to see is a "results validation" protocol.  This sheet would be identical to the results sheet, but showing all 3 values and the option to keep or discard any one or more of the values to be considered for the final results protocol.  Does that make sense?

**Comment by tim-snyder-wustl** [comment]
@mcordes-gtac Yes, but to be sure, in the .qpc file 'Concentration' is listed, but you want that labeled as 'Molarity' in the protocol?

**Comment by mcordes-gtac** [comment]
Molarity is calculated on the results sheet based on values in the .qpc file and Average Library Size (bp).  Not sure what magic ESP is using, but my assumption is that it takes an average of the 3 values and that is what is used to calculate molarity on the results page.  So, for the results _validation_ page, we would want to calculate molarity for all 3 values.   The results page would show a single averaged value based on what is selected to keep.

**Comment by tim-snyder-wustl** [comment]
@mcordes-gtac Right now, 'Average Concentration (ng/µl)' in the KAPA Results protocol is populated via the ingest script in the previous protocol. I'm guessing that will need to be re-caclulated based on the triplicates from this new protocol I will create, minus those samples that have failed the validation check?

**Comment by mcordes-gtac** [comment]
That sounds correct.  Also, when I said this in a previous comment 
_"Not sure what magic ESP is using, but my assumption is that it takes an average of the 3 values and that is what is used to calculate molarity on the results page. So, for the results validation page, we would want to calculate molarity for all 3 values. The results page would show a single averaged value based on what is selected to keep."_

You don't really have to calculate Molarity on the validation page.  We could just choose what values to keep (from the triplicates) based on 'Average Concentration (ng/ul)' ingested from the .qpc file.  Then take the average based on what is remaining and populate the 'Results' protocol with that.  Therefor not having to change anything really on the results protocol.

**Comment by tim-snyder-wustl** [comment]
For reference: 384 well plate triplicate layout for KAPA quantification:

![Image](https://user-images.githubusercontent.com/91081406/194156746-5166e6c2-1d48-449d-ba53-e3473a31b3d8.png)

**Comment by tim-snyder-wustl** [comment]
For reference, for the UI:

https://lodash.com/docs/4.17.15#template

`api.showModal(header, content, footer)` (HTML string | array of HTML nodes | a single HTML node)
`api.destroyModal()`
