### ISSUE TITLE
Report for Library Pools

### ISSUE THREAD

**Issue by tim-snyder-wustl** [GTAC-MGI/GTAC-ESP-LIMS#71]
General Note for several issues related to sample pooling.  Or at least issues with visualizing the pools and what is in them.

**Comment by tim-snyder-wustl** [comment]
Should this be a CSV or a custom web view?

**Comment by tim-snyder-wustl** [comment]
What's in this report? Where should this protocol live in the Workflow Chain? Are there any formulas / calculations?

**Comment by tim-snyder-wustl** [comment]
Need sample CSV / table with the fields needed from Matt. Can be a web view.

**Comment by mcordes-gtac** [comment]
Ideally, if we search for an Illumina Library Pool in ESP by it's ID and get to this page:

http://sandbox5.wucon.wustl.edu:11702/#/entities/details/b3538de3-1eb3-4f13-bbe5-88246087ef47/data

One of the tabs here could be the custom web view that would show the information in the attached sheet for each library in the pool.  If that is not possible, I am certainly open to suggestion on the best way to have this information available in ESP.

[Library Pool Report.csv](https://github.com/GTAC-MGI/GTAC-ESP-LIMS/files/9559104/Library.Pool.Report.csv)

**Comment by tim-snyder-wustl** [comment]
@mcordes-gtac Custom web view for the entity!


![Image](https://user-images.githubusercontent.com/91081406/191355035-c1eefba9-4410-4fcd-af83-3972394c6518.png)
