### ISSUE TITLE
Report for Dilutions

### ISSUE THREAD

**Issue by tim-snyder-wustl** [GTAC-MGI/GTAC-ESP-LIMS#74]
Information for dilutions taken from parent (ie, project, customer, general billing info) - does this information travel with sample through dilutions, pools etc.

Also: Manual Pooling, indexes associated with parent not pulled into this worksheet.  Need to grab these from somewhere else, or can this be retained somehow throughout the progression of the source.

Custom CSV report needed for now, but maybe a custom applet in the future.

**Comment by tim-snyder-wustl** [comment]
What's in this report? Where should this protocol live? Is there an example CSV? Does this need to be a report or could it just be a worksheet that can be exported?

**Comment by tim-snyder-wustl** [comment]
Need a template from Matt for what needs to be in report. Could be implemented in a custom web view.

**Comment by mcordes-gtac** [comment]
I think this ticket came about with a limited understanding of how metadata was retained for a particular library.  As I understand it, nothing really needs to be done to make sure all parent metadata is retained for a child (ie. dilution).  The metadata should be available for both parent and child throughout the process regardless the number of children, correct?  

I don't think a report is needed here, just the reassurance that metadata a retained for the child in the event it is needed, should a report be requested somewhere down the road using the child as input.

**Comment by tim-snyder-wustl** [comment]
@mcordes-gtac Yes, that's correct. ESP will keep track of sample heritage.
