### ISSUE TITLE
Unable to enter value for Normalized Molarity

### ISSUE THREAD

**Issue by tim-snyder-wustl** [GTAC-MGI/GTAC-ESP-LIMS#80]
Unable to enter value for Normalized Molarity. Attempting to enter 2nM, but getting the error "Normalized Molarity (nM) must be less than Molarity (nM)". Library molarity is much higher than 2nM?  And yet, it somehow still calculates volumes needed for the dilutions.

Worksheet: LLWGBS_Testing_02May2022   SEQ Lab: Manual Library Dilution

https://gtac-mgi-lims.wustl.edu/#/lims/worksheet/dca9c0e6-41b3-4f90-a153-cf47abc7ebd6

**Comment by LMT337** [comment]
Formula: 
 Volume to Add (ul) = (norm_mol * norm_vol) / molarity

Fail conditions:
out of bounds if the Volume to Add (ul) is >/= to the norm_vol

OnChange function in 'Normalized Molarity (nM)' column:

```let mol = api.getDataAt(row, "Molarity (nM)")
let norm_mol = api.getDataAt(row, "Normalized Molarity (nM)")
let norm_vol = api.getDataAt(row, "Normalized Volume (μL)")
if (mol && norm_mol && norm_mol > mol) {
  api.setDataAt(row, 'Normalized Molarity (nM)', '')
  api.showNotification('Normalized Molarity (nM) must be less than Molarity (nM)', 'error')
}
if (mol && norm_vol && norm_mol) {
let expr = `(${norm_mol} * ${norm_vol}) / ${mol}`
  api.evalExpression(expr, function(result) {
    api.setDataAt(row, 'Volume to Add (μL)', result.toFixed(1))
  })
}```

**Comment by LMT337** [comment]
```if (mol && norm_mol && norm_mol > mol)``` always evaluates to `True`, causing the the column value to be set to '', meaning no values can be entered.  

```if (mol && norm_vol && norm_mol)``` also evaluates to `True` meaning volumes are stil calculated as expected.

**Comment by LMT337** [comment]
"Molarity (nM)" column value added using ESP expression `{{ cell('Concentration (nM)', 'KAPA Library Quantification Results') }}`, column will have same error if value is changed after "Normalized Molarity (nM)" value added. JS for this column needs to be updated as well.
```if (mol && norm_mol && norm_mol > mol) {
  api.setDataAt(row, 'Molarity (nM)', '')
  api.showNotification('Normalized Molarity (nM) must be less than Molarity (nM)', 'error')
}```

**Comment by LMT337** [comment]
In addition, changed protocol name to add 'SEQ:', corrected yml file name using protocol naming convention and updated references to updated protocol name in other protocol/workflow/seed yml files.

**Comment by LMT337** [comment]
Tested make import after merging in release-4 branch.
Pushed and merged to gtac/release-4
